import type { Metadata } from "next";
import { Knewave, Sen, JetBrains_Mono, Source_Code_Pro } from 'next/font/google'
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Ayaka Miyazaki - Home",
  description: "Generated by create next app",
};

const knewave = Knewave({ weight: '400', subsets: ['latin'], display: 'swap' })
const sen = Sen({ weight: ['400','700','800'], subsets: ['latin'], display: 'swap' })
const jetbrainsMono = JetBrains_Mono({ weight: ['100','400','700','800'], subsets: ['latin'], display: 'swap' })
const sourceCode = Source_Code_Pro({ weight: ['200','400','700','900'], subsets: ['latin'], display: 'swap' })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-0">
        <div className="min-h-screen max-w-[2000px] mx-auto">
          <main>
            <Header />
            {children}
            <Footer isDark={true} />
          </main>
        </div>
      </body>
    </html>
  );
}
